/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppAside: typeof import('./src/components/AppAside.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    CardSearchParam: typeof import('./src/components/CardSearchParam.vue')['default']
    CardTable: typeof import('./src/components/CardTable.vue')['default']
    CompDateRangePicker: typeof import('./src/components/CompDateRangePicker.vue')['default']
    CompHtmlEditor: typeof import('./src/components/CompHtmlEditor.vue')['default']
    CompItemSelect: typeof import('./src/components/CompItemSelect.vue')['default']
    CompRadioSelect: typeof import('./src/components/CompRadioSelect.vue')['default']
    CompTextInput: typeof import('./src/components/CompTextInput.vue')['default']
    DialogAddEditImg: typeof import('./src/components/DialogAddEditImg.vue')['default']
    DialogAlert: typeof import('./src/components/DialogAlert.vue')['default']
    DialogErrorInfo: typeof import('./src/components/DialogErrorInfo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconLogo: typeof import('./src/components/icons/IconLogo.vue')['default']
    IconLogoTitle: typeof import('./src/components/icons/IconLogoTitle.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
